compiler                = gcc
src                     = download_server.c server.c
dst                     = server
cflags                  = -std=gnu11
lflags                  = -lpthread

main:
	${compiler} ${src} -o ${dst} ${cflags} ${lflags}
